### ISSUE TITLE
Output directory is cleared when compiling reports

### ISSUE THREAD

**Issue by bjorndarri** [f-cramer/jasperreports-gradle-plugin#9]
Hi, 

First of all, thanks for carrying on with this plugin, I've been managing a rather ugly custom Gradle task for this purpose, glad to be rid of it.

Anyway, in one of my projects I'm using `buildDir/resources/main/some/package` as output directory, which works fine, but the package in question contains a bunch of other resource files, which then get deleted.

I found the culprit and fixed it by restricting the deletion to files ending with the task output extension.

[JasperReportsCompileTask.kt#L100](https://github.com/f-cramer/jasperreports-gradle-plugin/blob/b11e36d279fe729f858330652beafeece74f1510/src/main/kotlin/com/github/fcramer/gradle/jasperreports/tasks/JasperReportsCompileTask.kt#L100)
```
// delete all output if not incremental
if (!inputs.isIncremental) {
    outDir.asFileTree.visit {
        if (!isDirectory && path.endsWith(outExt.get())) {
            file.delete()
        }
    }
}
```
Let me know if you want me to create a pull-request.

**Comment by tschulte** [comment]
You should always only have one task write to any directory. Otherwise you will run into problems with up-to-date checks and when using the gradle build cache. I bet in your setup most of the times the build is not incremental although it should be.

You should configure each task to write into its own directory and have a separate task combine the output into a new directory, if you need it combined. That one task to combine the results might be the existing processResources task.

E.g. in my case I would configure this plugin like this:

```groovy
jasperreports {
    // I want to use classes from src/main/java in the reports
    classpath.from(project.sourceSets.main)
}
// the generated .jasper files should end up in the jar
sourceSets.main.resources.srcDir(task)
```

The above also implicitly creates all the correct task dependencies, i.e. compileAllReports dependsOn compileJava, and processResources depends on compileAllReports.

**Comment by bjorndarri** [comment]
Excellent, I had a feeling something was not quite correct since I had to set up a bunch of task dependencies for things to work correctly.

Thanks!

**Comment by bjorndarri** [comment]
Hi again,

I'm so sorry about resurrecting this non-issue, but I haven't managed to get the compiled reports on the classpath like you suggested, due to a circular task dependency (and of course my lack of knowledge when it comes to Gradle).

I tried asking this question on the Gradle discussion forums, since this is a somewhat generic problem, but I haven't received any replies so here we are :|.

Below you'll find the question I posed on the Gradle forums and a link to a minimal github project demonstrating the problem:

[minimal demo project](https://github.com/bjorndarri/jasperreports-plugin-test)

**Gradle forums question:**

I have a problem with circular task dependencies in a [very simple build file](https://github.com/bjorndarri/jasperreports-plugin-test/blob/main/build.gradle).

I'm using [jasperreports-gradle-plugin](https://github.com/f-cramer/jasperreports-gradle-plugin), which provides a task `compileAllReports` for compiling report designs into reports.

One of my reports uses a class from `src/main/java`, so the report compilation task depends on the `runtimeClasspath` (which also contains the required JasperReports library jars).

The plugin provides a way to do that:
```
jasperreports {
    classpath.from(project.sourceSets.main.runtimeClasspath)
}
```
But now I need those compiled reports available as resources on the classpath.

So I tried to add the following:
```
sourceSets.main.resources.srcDir(compileAllReports)
```
But now I get the following error:
```
Circular dependency between the following tasks:
:classes
\--- :processResources
     \--- :compileAllReports
          \--- :classes (*)
```
This does make sense, but I'm wondering if there is a way to achieve what I'm trying to do?

**Comment by f-cramer** [comment]
The only way I see to use "custom" classes while also compiling the report into a jar is to split the project into two modules. One contains all custom java files, while the other one contains only the report. You can then add the first module to the jasperreports classpath. I [forked your demo project](https://github.com/f-cramer/jasperreports-plugin-test/tree/multiple-modules) and it seems to work.

If anyone has a better / another idea please share it here.

**Comment by bjorndarri** [comment]
Given all the things I've experimented with, trying to get this working, sort of prepared me for this answer :smile:.

Splitting the project into modules is a great idea though, I'll try that out tomorrow.

Thanks for the help, I'll be sure to report back if I ever come across a solution.

**Comment by bjorndarri** [comment]
Hey, guess what, a solution was posted on the Gradle forums thread.

https://discuss.gradle.org/t/circular-task-dependencies-when-adding-compiled-reports-to-classpath/48912/2
